// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImportStatusController from "./import_status_controller"
application.register("import-status", ImportStatusController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import NutritionController from "./nutrition_controller"
application.register("nutrition", NutritionController)

import IngredientsController from "./ingredients_controller"
application.register("ingredients", IngredientsController)

import OcrController from "./ocr_controller"
application.register("ocr", OcrController)

import PushNotificationsController from "./push_notifications_controller"
application.register("push-notifications", PushNotificationsController)

import RatingController from "./rating_controller"
application.register("rating", RatingController)

import StepsController from "./steps_controller"
application.register("steps", StepsController)

import WakeLockController from "./wake_lock_controller"
application.register("wake-lock", WakeLockController)
